FROM node:lts-alpine AS builder
WORKDIR /app
COPY *.json .
COPY *.html .
COPY *.ts .
RUN npm install
COPY src src
RUN npm run build

FROM nginx:alpine
RUN apk --no-cache add curl
COPY --from=builder /app/dist/ /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

