FROM node:lts-alpine AS builder
WORKDIR /app
COPY *.json .
COPY *.html .
COPY *.ts .
RUN npm install
RUN npm run build

FROM node:lts-alpine
WORKDIR /app
RUN apk --no-cache add curl
COPY --from=builder /app/dist/ ./build
COPY package*.json .
RUN npm install --production
CMD ["npm", "run", "start"]

