services:
  frontend-prod:
    restart: always
    container_name: frontend-prod
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    healthcheck:
      interval: 5s 
      retries: 3
      start_period: 10s
      test:
        [
          "CMD-SHELL",
          "curl --fail --request GET --url 'http://frontend-prod:5173' || exit 1",
        ]
    depends_on:
      backend-prod:
        condition: service_healthy

  backend-prod:
    restart: always
    container_name: backend-prod
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    healthcheck:
      retries: 3
      test:
        [
          "CMD-SHELL",
          'curl --fail --request POST --header ''Content-Type: application/json'' --url ''http://backend-prod:3000'' --data ''{"query":"query { __typename }"}'' || exit 1',
        ]
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      JWT_SECRET: ${JWT_SECRET}

  database:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - ./persist/database:/var/lib/postgresql/data

  # Permet d'accéder au front, back et db depuis un même port qui "distribue" les demandes en fonction de l'URL. Nécessaire pour pouvoir utiliser un JWT site strict
  gateway:
    image: nginx
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
    ports:
      # Gateway port => "extérieur" de la porte du container : 80 => "intérieur" de la porte du container
      - ${GATEWAY_PORT}:80
    depends_on:
      backend-prod:
        condition: service_healthy
      frontend-prod:
        condition: service_healthy

  adminer:
    image: adminer
    depends_on:
      database:
        condition: service_healthy
