services:

  database-stage:
    container_name: database-stage
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
      interval: 20s 
      timeout: 10s
      retries: 5
      start_period: 100s
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - ./persist/database-stage:/var/lib/postgresql

  backend-stage:
    restart: always
    container_name: backend-stage
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_PROJECT_NAME}:backend-latest
    healthcheck:
      interval: 20s
      retries: 10
      timeout: 15s
      start_period: 120s
      test:
        [
          "CMD-SHELL",
          'curl --fail --request POST --header ''Content-Type: application/json'' --url ''http://backend-stage:3000'' --data ''{"query":"query { __typename }"}'' || exit 1',
        ]
    environment: # peut être mettre les id de docker
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      database-stage:
        condition: service_healthy

  frontend-stage:
    restart: always
    container_name: frontend-stage
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_PROJECT_NAME}:frontend-latest
    healthcheck:
      interval: 20s 
      retries: 15
      timeout: 20s
      start_period: 120s
      test:
        [
          "CMD-SHELL",
          "curl --fail --request GET --url 'http://frontend-stage:80' || exit 1",
        ]
    depends_on:
      backend-stage:
        condition: service_healthy

  # Permet d'accéder au front, back et db depuis un même port qui "distribue" les demandes en fonction de l'URL. Nécessaire pour pouvoir utiliser un JWT site strict
  gateway-stage:
    container_name: gateway-stage
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      # Gateway port => "extérieur" de la porte du container : 80 => "intérieur" de la porte du container
      - ${GATEWAY_PORT}:80
    depends_on:
      backend-stage:
        condition: service_healthy
      frontend-stage:
        condition: service_healthy

