services:
  frontend-dev:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    volumes:
      - ./frontend/src/:/app/src/
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --request GET --url 'http://frontend-dev:5173' || exit 1",
        ]
    depends_on:
      backend-dev:
        condition: service_healthy

  backend-dev:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'curl --fail --request POST --header ''Content-Type: application/json'' --url ''http://backend-dev:3000'' --data ''{"query":"query { __typename }"}'' || exit 1',
        ]
    environment:
      DB_PASSWORD: ${secrets.DOCKERHUB_TEST_DB_PASSWORD}
      DB_DATABASE: ${secrets.DOCKERHUB_TEST_DB_DATABASE}
      DB_USER: ${secrets.DOCKERHUB_TEST_DB_USER}
      DB_HOST: ${secrets.DOCKERHUB_TEST_DB_HOST}
      JWT_SECRET: ${secrets.DOCKERHUB_TEST_JWT_SECRET}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USER}"]
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PASSWORD: ${secrets.DOCKERHUB_TEST_DB_PASSWORD}
      POSTGRES_DB: ${secrets.DOCKERHUB_TEST_DB_DATABASE}
      POSTGRES_USER: ${secrets.DOCKERHUB_TEST_DB_USER}
      POSTGRES_HOST: ${secrets.DOCKERHUB_TEST_DB_HOST}