events {}

http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        server {
                listen 80;
                server_name _;

                root /usr/share/nginx/html;
                index index.html;

                location /api {
                        proxy_pass http://backend-stage:3000;
                }

                location / {
                        # Frontend is served by nginx on port 80 inside the container
                        # root /usr/share/nginx/html;
                        try_files $uri $uri/ /index.html;
                }
        }
}