FROM node:lts-alpine AS builder
WORKDIR /app
COPY src src
COPY *.json .
RUN npm install
RUN npm run build

FROM node:lts-alpine
WORKDIR /app
RUN apk --no-cache add curl
COPY --from=builder /app/dist ./build
COPY package*.json .
RUN npm ci --omit=dev
CMD ["npm", "run", "prod"]

