FROM node:lts-alpine3.22
WORKDIR /app

# Installe curl pour les healthchecks
RUN apk --no-cache add curl

# Copie du src locale vers le src du container docker
COPY src src
COPY upload-image-service upload-image-service
COPY images images

# Copie des packages files 
COPY *.json .
COPY ./upload-image-service/*.json ./upload-image-service

# Installations des dépendances
RUN npm i

# Lance la commande de lancement du serveur (développement)
CMD ["npm", "run", "start"]